### ISSUE TITLE
Missing Call On Method

### ISSUE THREAD

**Issue by AssanSav** [learn-co-curriculum/programming-univbasics-3-methods-scope#2]
def my_ruby_method 
  local_variable = 'Hello World!'
  puts local_variable
end
MISSING CALL ON <my_ruby_method>
# => Hello World!
Now if you run this code in IRB, you will see the out*put* "Hello World!". But even if you didn't use puts on local_variable, for a brief second, as my_ruby_method the variable would exist in the method's local scope.

**Comment by sgharms** [comment]
Thanks! Fixed as of 4ad56f6
