### ISSUE TITLE
missing quotes

### ISSUE THREAD

**Issue by ryanmeinzer** [learn-co-curriculum/programming-univbasics-3-methods-scope#4]
2.6.1 :003 > puts Hello! 

should be

2.6.1 :003 > puts "Hello!"

**Comment by maxwellbenton** [comment]
Hi @ryanmeinzer,

Thank you for spotting this and providing feedback. We've updated the lesson this typo was in (https://github.com/learn-co-curriculum/programming-univbasics-3-methods-default-values-lab) and believe this issue is now resolved.

Thank you for contributing to a Learn lesson!
