### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by tbartelsmeyer** [learn-co-curriculum/programming-univbasics-3-methods-scope#5]
<img width="420" alt="Screen Shot 2020-05-16 at 7 41 36 PM" src="https://user-images.githubusercontent.com/47281160/82133105-43bfc880-97ad-11ea-8be0-781a69ee4bf8.png">
I think that the second "Why can't be used here" line should be can instead.

**Comment by maxwellbenton** [comment]
Hi @tbartelsmeyer,

Thank you for catching this error and providing feedback! We've fixed this code snippet typo so that it indicates `why` _can_ be used inside the method, which should resolve this issue.

Thank you for contributing to a Learn lesson!
